CREATE DATABASE IF NOT EXISTS ruleta;

USE ruleta;

CREATE TABLE IF NOT EXISTS apuestas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(255) NOT NULL,
  numero VARCHAR(255) NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP
);
